# Generated by Django 2.0.9 on 2018-12-06 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='字段说明')),
                ('content', models.TextField(null=True, verbose_name='内容')),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('changetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '基础配置',
                'verbose_name_plural': '基础配置',
            },
        ),
        migrations.CreateModel(
            name='BMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='留言标题')),
                ('content', models.TextField(blank=True, null=True, verbose_name='留言内容')),
                ('settime', models.DateTimeField(blank=True, null=True, verbose_name='留言时间')),
                ('ipaddress', models.CharField(blank=True, max_length=255, null=True, verbose_name='ip地址')),
            ],
            options={
                'verbose_name': '群众留言',
                'verbose_name_plural': '群众留言',
            },
        ),
        migrations.CreateModel(
            name='BMessageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='留言类型')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rd.BMessageType', verbose_name='父级类型')),
            ],
            options={
                'verbose_name': '留言类型',
                'verbose_name_plural': '留言类型',
            },
        ),
        migrations.CreateModel(
            name='BUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='姓名')),
                ('account', models.CharField(blank=True, max_length=255, null=True, verbose_name='账号')),
                ('passwrod', models.CharField(blank=True, max_length=255, null=True, verbose_name='密码')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='电话')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='')),
                ('type', models.IntegerField(default=1, verbose_name='用户类型')),
            ],
            options={
                'verbose_name': '系统用户',
                'verbose_name_plural': '系统用户',
            },
        ),
        migrations.CreateModel(
            name='BUserListType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='类型名称')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rd.BUserListType', verbose_name='父类名称')),
            ],
            options={
                'verbose_name': '领导名册类型',
                'verbose_name_plural': '领导名册类型',
            },
        ),
        migrations.AddField(
            model_name='bmessage',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rd.BMessageType', verbose_name='留言类型'),
        ),
        migrations.AddField(
            model_name='bmessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rd.BUser', verbose_name='留言人'),
        ),
    ]
